export const NEXT_PUBLIC_MODE = process.env.NEXT_PUBLIC_MODE;

export const JWT_SECRET = process.env.JWT_SECRET!;

export const NEXT_PUBLIC_BASE_URL = process.env.NEXT_PUBLIC_BASE_URL!;

export const OPENAI_SECRET_KEY = process.env.OPENAI_SECRET_KEY!;
export const NEXT_PUBLIC_OPENAI_CHAT_COMPLETION_MODEL =
  process.env.NEXT_PUBLIC_OPENAI_CHAT_COMPLETION_MODEL!;
export const NEXT_PUBLIC_OPENAI_EMBEDDING_MODEL =
  process.env.NEXT_PUBLIC_OPENAI_EMBEDDING_MODEL!;

export const STRIPE_PRODUCT_BASIC_ID = process.env.STRIPE_PRODUCT_BASIC_ID!;
export const STRIPE_PRODUCT_PREMIUM_ID = process.env.STRIPE_PRODUCT_PREMIUM_ID!;
export const STRIPE_PRODUCT_ENTERPRISE_ID =
  process.env.STRIPE_PRODUCT_ENTERPRISE_ID!;
export const NEXT_PUBLIC_STRIPE_PRICING_TABLE_ID =
  process.env.NEXT_PUBLIC_STRIPE_PRICING_TABLE_ID!;
export const NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY =
  process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY!;
export const STRIPE_SECRET_KEY = process.env.STRIPE_SECRET_KEY!;

export const STRIPE_WEBHOOK_SECRET = process.env.STRIPE_WEBHOOK_SECRET!;

export const SESSION_SECRET = process.env.SESSION_SECRET!;

export const NEXT_PUBLIC_SOURCES_WEBSITE =
  process.env.NEXT_PUBLIC_SOURCES_WEBSITE!;
export const NEXT_PUBLIC_SOURCES_FILES_TYPES =
  process.env.NEXT_PUBLIC_SOURCES_FILES_TYPES!;
export const NEXT_PUBLIC_SOURCES_FILES_SIZE_MB =
  process.env.NEXT_PUBLIC_SOURCES_FILES_SIZE_MB!;

export const NEXT_PUBLIC_GOOGLE_ANALYTICS_ID =
  process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID;
export const NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID =
  process.env.NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID;
